# Generated by Django 3.2 on 2021-04-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='random_order',
            new_name='_order',
        ),
        migrations.RemoveField(
            model_name='question',
            name='figure',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='url',
            field=models.CharField(help_text='a user friendly url', max_length=60, verbose_name='user friendly url'),
        ),
    ]
