# Generated by Django 3.2 on 2021-04-20 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210420_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='_order',
            new_name='random_order',
        ),
    ]
